name: main
on: [push, pull_request]
jobs:
  
  vars:
    name: Setup environment variables
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.vars.outputs.tag }}
    steps:
      - id: vars
        # run: echo "::set-output name=tag::$(git show -s --format="%h")"
        run: |
          if [[ ! "$GITHUB_REF" =~ refs/tags ]]; then
            echo "::set-output name=tag::$(echo $GITHUB_SHA | cut -c 1-8)"
          else
            echo "::set-output name=tag::$(echo $GITHUB_REF | cut -d / -f 3)"
          fi
      - run: echo ${{ steps.vars.outputs.tag }}
  
  test:
    runs-on: ubuntu-latest
    needs: 
      - vars
    strategy:
      matrix:
        go: ["1.17", "1.18"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 
      - run: go test -v ./...
  
  docker:
    name: Build and Push
    needs:
      - vars
      - test
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v2
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
       - name: Login to DockerHub
         uses: docker/login-action@v2
         with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
       - name: Build and push
         uses: docker/build-push-action@v3
         with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/testgoapp:${{ needs.vars.outputs.tag }}
  
  slack-workflow-status:
    if: always()
    name: Post Workflow Status To Slack
    needs:
      - vars
      - test
      - docker
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          # Required Input
          repo_token: ${{secrets.ACCESS_TOKEN_GITHUB}}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK }}
          # Optional Input
          channel: 'github-notifications'
          name: 'github-notifications'
          icon_emoji: ':rocket:'
          icon_url: 'https://avatars0.githubusercontent.com/u/1701160?s=96&v=4'
