name: main
on: [push, pull_request]
jobs:
  
  vars:
    name: Setup environment variables
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.vars.outputs.tag }}
    steps:
      - id: vars
        # run: echo "::set-output name=tag::$(git show -s --format="%h")"
        run: |
          if [[ ! "$GITHUB_REF" =~ refs/tags ]]; then
            echo "::set-output name=tag::$(echo $GITHUB_SHA | cut -c 1-8)"
          else
            echo "::set-output name=tag::$(echo $GITHUB_REF | cut -d / -f 3)"
          fi
      - run: echo ${{ steps.vars.outputs.tag }}
  
  test:
    runs-on: ubuntu-latest
    needs: 
      - vars
    strategy:
      matrix:
        go: ["1.17", "1.18"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 
      - run: go test -v ./...
  
  slack-workflow-status:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: workflow-notification
        SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: 'App is ready for development :rocket:'
        SLACK_TITLE: New App Status
        SLACK_USERNAME: github-notifications
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
